#!/bin/bash
mv btn-unpin-a.xcf.xpm btn-unpin-a.xpm
mv btn-unshade-a.xcf.xpm btn-unshade-a.xpm
mv btn-shade-a-push.xcf.xpm btn-shade-a-push.xpm
mv headerbg-i.xcf.xpm headerbg-i.xpm
mv gripper-tall-i.xcf.xpm gripper-tall-i.xpm
mv btn-shade-a.xcf.xpm btn-shade-a.xpm
mv btn-max-i.xcf.xpm btn-max-i.xpm
mv btn-close-i-push.xcf.xpm btn-close-i-push.xpm
mv btn-close-a.xcf.xpm btn-close-a.xpm
mv btn-max-i-push.xcf.xpm btn-max-i-push.xpm
mv btn-shade-i-push.xcf.xpm btn-shade-i-push.xpm
mv btn-min-i.xcf.xpm btn-min-i.xpm
mv btn-unshade-i.xcf.xpm btn-unshade-i.xpm
mv btn-pin-i.xcf.xpm btn-pin-i.xpm
mv btn-close-i.xcf.xpm btn-close-i.xpm
mv btn-unpin-i.xcf.xpm btn-unpin-i.xpm
mv btn-max-a-push.xcf.xpm btn-max-a-push.xpm
mv gripper-short-a.xcf.xpm gripper-short-a.xpm
mv btn-pin-a.xcf.xpm btn-pin-a.xpm
mv btn-min-i-push.xcf.xpm btn-min-i-push.xpm
mv headerbg-a.xcf.xpm headerbg-a.xpm
mv gripper-short-i.xcf.xpm gripper-short-i.xpm
mv btn-shade-i.xcf.xpm btn-shade-i.xpm
mv footerbg-a.xcf.xpm footerbg-a.xpm
mv gripper-short-a-push.xcf.xpm gripper-short-a-push.xpm
mv gripper-tall-a.xcf.xpm gripper-tall-a.xpm
mv btn-max-a.xcf.xpm btn-max-a.xpm
mv btn-min-a-push.xcf.xpm btn-min-a-push.xpm
mv btn-min-a.xcf.xpm btn-min-a.xpm
mv gripper-short-i-push.xcf.xpm gripper-short-i-push.xpm
mv btn-close-a-push.xcf.xpm btn-close-a-push.xpm
